http:
  routers:
    jonathan-loescher-production-eguexh-router-1:
      rule: Host(`staging.jonathanloescher.com`)
      service: jonathan-loescher-production-eguexh-service-1
      middlewares:
        - redirect-to-https
        - auth-jonathan-loescher-production-eguexh
      entryPoints:
        - web
    jonathan-loescher-production-eguexh-router-websecure-1:
      rule: Host(`staging.jonathanloescher.com`)
      service: jonathan-loescher-production-eguexh-service-1
      middlewares:
        - auth-jonathan-loescher-production-eguexh
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
  services:
    jonathan-loescher-production-eguexh-service-1:
      loadBalancer:
        servers:
          - url: http://jonathan-loescher-production-eguexh:80
        passHostHeader: true
