http:
  routers:
    jonathan-loescher-production-iekjoq-router-1:
      rule: Host(`jonathanloescher.com`)
      service: jonathan-loescher-production-iekjoq-service-1
      middlewares:
        - redirect-to-https
      entryPoints:
        - web
    jonathan-loescher-production-iekjoq-router-websecure-1:
      rule: Host(`jonathanloescher.com`)
      service: jonathan-loescher-production-iekjoq-service-1
      middlewares: []
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
  services:
    jonathan-loescher-production-iekjoq-service-1:
      loadBalancer:
        servers:
          - url: http://jonathan-loescher-production-iekjoq:80
        passHostHeader: true
