include 'postgresql.base.conf'
cluster_name = 'quantyra_pg'
effective_cache_size = '24GB'
hot_standby = 'on'
listen_addresses = '127.0.0.1,100.115.75.119'
maintenance_work_mem = '2GB'
max_connections = '200'
max_locks_per_transaction = '64'
max_prepared_transactions = '0'
max_replication_slots = '10'
max_wal_senders = '10'
max_worker_processes = '8'
port = '5432'
shared_buffers = '8GB'
synchronous_commit = 'off'
track_commit_timestamp = 'off'
unix_socket_directories = '/var/run/postgresql'
wal_keep_size = '8GB'
wal_level = 'replica'
wal_log_hints = 'on'
work_mem = '64MB'
hba_file = '/etc/postgresql/18/main/pg_hba.conf'
ident_file = '/etc/postgresql/18/main/pg_ident.conf'
primary_conninfo = 'dbname=postgres user=patroni_repl passfile=/var/lib/postgresql/.pgpass_patroni host=100.126.103.51 port=5432 sslmode=prefer application_name=re-node-04 gssencmode=prefer channel_binding=prefer sslnegotiation=postgres'
primary_slot_name = 're_node_04'
recovery_target = ''
recovery_target_lsn = ''
recovery_target_name = ''
recovery_target_time = ''
recovery_target_timeline = 'latest'
recovery_target_xid = ''
