# renew_before_expiry = 30 days
version = 2.9.0
archive_dir = /etc/letsencrypt/archive/hooks.quantyralabs.cc
cert = /etc/letsencrypt/live/hooks.quantyralabs.cc/cert.pem
privkey = /etc/letsencrypt/live/hooks.quantyralabs.cc/privkey.pem
chain = /etc/letsencrypt/live/hooks.quantyralabs.cc/chain.pem
fullchain = /etc/letsencrypt/live/hooks.quantyralabs.cc/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 8b3728be973dcb587b140c6da87b1b9f
authenticator = dns-cloudflare
dns_cloudflare_credentials = /root/.secrets/cloudflare.ini
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
