# renew_before_expiry = 30 days
version = 2.9.0
archive_dir = /etc/letsencrypt/archive/staging.rentalfixer.app
cert = /etc/letsencrypt/live/staging.rentalfixer.app/cert.pem
privkey = /etc/letsencrypt/live/staging.rentalfixer.app/privkey.pem
chain = /etc/letsencrypt/live/staging.rentalfixer.app/chain.pem
fullchain = /etc/letsencrypt/live/staging.rentalfixer.app/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 28a35bc03d5b1250e08f7884baf2bc9d
authenticator = dns-cloudflare
dns_cloudflare_credentials = /root/.secrets/cloudflare.ini
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
