[jonathanloescher-staging]
user = webapps
group = www-data
listen = /run/php/php8.5-fpm-jonathanloescher-staging.sock
listen.owner = www-data
listen.group = www-data
pm = dynamic
pm.max_children = 80
pm.start_servers = 10
pm.min_spare_servers = 5
pm.max_spare_servers = 20
pm.max_requests = 500
