bind 100.114.117.46
port 6379
protected-mode yes
requirepass CcPUa3nvcxHtyNYjztbDyfCCuhgix78novmBDNGk
masterauth CcPUa3nvcxHtyNYjztbDyfCCuhgix78novmBDNGk
replicaof 100.126.103.51 6379
maxmemory 2gb
maxmemory-policy allkeys-lru
save 900 1
save 300 10
save 60 10000
appendonly yes
appendfsync everysec
loglevel notice
logfile /var/log/redis/redis-server.log
databases 16
timeout 0
tcp-keepalive 300
daemonize no
supervised systemd
pidfile /run/redis/redis-server.pid
dir /var/lib/redis
