apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://100.102.220.16:3100
    isDefault: false
    editable: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: TraceID
          matcherRegex: '"traceId":"(\w+)"'
          url: '$${__value.raw}'