global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'quantyra'
    environment: 'production'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - '100.102.220.16:9093'

rule_files:
  - '/etc/prometheus/rules/*.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['100.126.103.51:9100']
        labels: {node: 're-node-01', role: 'database'}
      - targets: ['100.114.117.46:9100']
        labels: {node: 're-node-03', role: 'database'}
      - targets: ['100.115.75.119:9100']
        labels: {node: 're-node-04', role: 'database'}
      - targets: ['100.102.220.16:9100']
        labels: {node: 'router-01', role: 'router'}
      - targets: ['100.116.175.9:9100']
        labels: {node: 'router-02', role: 'router'}
      - targets: ['100.92.26.38:9100']
        labels: {node: 're-db', role: 'app'}
      - targets: ['100.89.130.19:9100']
        labels: {node: 're-node-02', role: 'app'}

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['100.126.103.51:9187']
        labels: {node: 're-node-01'}
      - targets: ['100.114.117.46:9187']
        labels: {node: 're-node-03'}
      - targets: ['100.115.75.119:9187']
        labels: {node: 're-node-04'}

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['100.126.103.51:9121']
        labels: {node: 're-node-01'}
      - targets: ['100.114.117.46:9121']
        labels: {node: 're-node-03'}

  - job_name: 'haproxy_exporter'
    static_configs:
      - targets: ['100.102.220.16:9101']
        labels: {node: 'router-01'}
      - targets: ['100.116.175.9:9101']
        labels: {node: 'router-02'}

  - job_name: 'patroni'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['100.126.103.51:8008']
        labels: {node: 're-node-01'}
      - targets: ['100.114.117.46:8008']
        labels: {node: 're-node-03'}
      - targets: ['100.115.75.119:8008']
        labels: {node: 're-node-04'}

  - job_name: 'etcd'
    static_configs:
      - targets: ['100.102.220.16:2379']
        labels: {node: 'router-01'}
      - targets: ['100.116.175.9:2379']
        labels: {node: 'router-02'}
      - targets: ['100.115.75.119:2379']
        labels: {node: 're-node-04'}



  - job_name: 'traefik'
    static_configs:
      - targets: ['100.92.26.38:80']
        labels: {node: 're-db', role: 'traefik'}
    metrics_path: /metrics

  - job_name: 'docker'
    static_configs:
      - targets: ['100.92.26.38:9323']
        labels: {node: 're-db', role: 'docker'}
      - targets: ['100.89.130.19:9323']
        labels: {node: 're-node-02', role: 'docker'}
    metrics_path: /metrics
