[Service]
Environment="CONFIG=/etc/haproxy/haproxy.cfg /etc/haproxy/domains"
ExecStart=
ExecStart=/usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -f /etc/haproxy/domains -p /run/haproxy.pid -S /run/haproxy-master.sock
ExecReload=
ExecReload=/usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -f /etc/haproxy/domains -c -q
ExecReload=/bin/kill -USR2 $MAINPID
